# # CLI settings 
# API_ID : 15395640
# API_HASH : "342d15c979a8c8384cd42bdb49b1a424"

# #API SETTINGS
# BOT_TOKEN : "7476343605:AAEz6Yo-35df0JAdbjIp_-FMGA_zX2efcgE"




# ADMINS : 
#   - 5361491365
#   - 1058811011




# FORCE_JOIN_CHANNEL : "https://t.me/crwpace"


# FORCE_JOIN_CHANNEL_ID : -1002162063893

# POST_CHANNEL : ""


# CLI settings 
API_ID : 15395640
API_HASH : "342d15c979a8c8384cd42bdb49b1a424"

#API SETTINGS
BOT_TOKEN : "7142012125:AAHlSGZiO40Mu6v2X4LcCSJqFcLFqNk4rpM"




ADMINS : 
  - 5361491365
  - 1158753501




FORCE_JOIN_CHANNEL : "https://t.me/cryptaldemo"


FORCE_JOIN_CHANNEL_ID : -1002075798363

POST_CHANNEL : ""
